### ISSUE TITLE
Broken link for past SWIBs

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#12]
Reported today by R.S.M. via email:

On 24.04.23 11:38, Santos Muñoz, Ricardo wrote:
> Hello, I was trying to reference, for a bibliography, a presentation 
> from an old SWIB, but they all seem to be unreachable (see the links in 
> https://swib.org/history.html <https://swib.org/history.html> to SWIB 
> 2021 and older).

I guess, we are missing some webserver configuration that happened at ZWB.

**Comment by acka47** [comment]
> I guess, we are missing some webserver configuration that happened at ZWB.

At least for SWIB22 and SWIB21. I think the problem is a different one with regard to SWIB20 and the ones before that.

**Comment by Phu2** [comment]
Some files for SWIB21 are missing eg. `index.md`. Therefore i don't know how to re-create the html files. For the older SWIB sites we have no source files at all.

**Comment by Phu2** [comment]
For referencing the archived sites at the Internet Archive might even the better choice. See https://web.archive.org/web/*/swib.org/ and https://web.archive.org/web/*/www.swib09.de/

**Comment by Phu2** [comment]
Brought back older sites using tgz archives.
@acka47 Please have a look at https://swib.org/swib23/history.html

**Comment by acka47** [comment]
Great. That was quick! And the slides are also already there. Perfect. +1 Closing.
