### ISSUE TITLE
SWIB22 web pages are out of date

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#13]
- [programme](https://swib.org/swib22/programme.html) is missing
- [speakers](https://swib.org/swib22/speakers.html) as well

**Comment by Phu2** [comment]
Updated. @acka47 Please have a look.
(The outdated pages were accidently pulled in during restore from old backup files.)

**Comment by acka47** [comment]
Thanks, it works again. Closing. Ping @annakasprzik as she reported it to me while someone else had reported it to her.

> The outdated pages were accidently pulled in during restore from old backup files.

I thought that this had happened.
