### ISSUE TITLE
SWIB22 slides are missing

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#18]
Reported by @lake44me via email:

On 13.06.23 23:28, L.A. wrote:
> I wanted to look at the slides from the presentation “BIBFRAME for 
> academic publishing in psychology” from SWIB 2022 – because I was short 
> on time to watch the whole video – but the link to the slides leads to a 
> “file not found” message. 
> https://swib.org/swib22/slides/Bibframe%20for%20academic%20publishing%20in%20psychology_no_animation_pages.pdf.  Had impulse to check slide links for other presentations in the programme page <https://swib.org/swib22/programme.html>, and I got the same message.  Thought you should know if you don’t already.  Let me know if you fix it please.

**Comment by Phu2** [comment]
Not sure what happened with the slides... need to investigate further. 
@lake44me Please have a look at https://web.archive.org/web/20230208155749/https://swib.org/swib22/slides/Bibframe%20for%20academic%20publishing%20in%20psychology_no_animation_pages.pdf for now.

**Comment by acka47** [comment]
Thanks, @Phu2, for putting the slides back online. All the links work again. Closing
