### ISSUE TITLE
Produktive SWIB-Webseite auf hbz-Servern aufsetzen

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#2]
Innerhalb der nächsten zwei Wochen. 

- [x] set up on test server
- [x]  transfer domain swib.org
- [x] get SSL certificate and install it
- [x] set up on productive server

**Comment by acka47** [comment]
@dr0i Can you please share the link to the site so that we cann review it?

**Comment by dr0i** [comment]
http://swib.test.metadaten.nrw/

**Comment by dr0i** [comment]
Asked at 17th March to transfer domain. After that we need a SSL certificate.

**Comment by Phu2** [comment]
Domain transfer completed. Still waiting for DFN/Sectigo to sign the SSL certificate.

**Comment by Phu2** [comment]
SSL certificate installed on April 14.

**Comment by Phu2** [comment]
Switched to prod server.
