### ISSUE TITLE
Link "Data protection" in SWIB23 footer to hbz Datenschutz 

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#37]
To Do:

- Remove the page https://swib.org/swib23/data_protection.html
- For all SWIB23 pages, i.e. those starting with https://swib.org/swib23/, link the footer text "Data protection" to https://www.hbz-nrw.de/datenschutz

**Comment by dr0i** [comment]
Did that. Please check.

**Comment by acka47** [comment]
+1 Closing

**Comment by dr0i** [comment]
Executing the scripts `./get_conftool_data.sh  && perl create_website.pl` brings back the wrong , internal link to "data protection". 
I don't know why - maybe this link is denoted in the Conftool @jneubert ?

**Comment by jneubert** [comment]
Conftool is not involved here. The `<header`> and `<footer>` elements of the web pages are defined in the Pandoc template (https://github.com/swibcon/swib.org/blob/main/etc/pandoc_templates/swibweb.html5), so the change has to be inserted there, and is effective with the next execution of Pandoc (via make).

**Comment by dr0i** [comment]
Thx @jneubert for the hint - fixed it with [f10e2f2](https://github.com/swibcon/swib.org/commit/f10e2f2068fee095372a7e3fd94161794925f7b7). Overlooked the template definition in the https://github.com/swibcon/swib.org/tree/main/bin#readme - besides the two exclamation marks :/ . (Was grep-ing for the pattern myself but apparently in the wrong directory).
