### ISSUE TITLE
Domain transfer

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#4]
From ZBW to hbz, planned for 2023-04-03.

**Comment by dr0i** [comment]
Mailed to IT:
"wir wollen die Domain swib.org zu uns umziehen.
Sie wird momentan vom ZBW verwaltet.
Was ist dafür nötig?

Dann brauchen wir auch noch ein SSL-Zertifikat - das alte Zertifikat kann wohl nicht einfach kopiert werden?"

**Comment by Phu2** [comment]
According to `whois swib.org` the status is now at https://icann.org/epp#transferPeriod

**Comment by acka47** [comment]
As discussed today:

- Tomorrow, the hbz version of the website will be updated with #8 .
- On Wednesday @Phu2 will inform @jneubert until 10 am whether the SSL certificate is there and whether the DNS entry was updated.
- On Thursday, we will update the page with the new submission deadline.

**Comment by Phu2** [comment]
SSL certificate is not available yet.

**Comment by Phu2** [comment]
Regarding the SSL certificate see https://github.com/swibcon/swib.org/issues/2

**Comment by Phu2** [comment]
Domain transfer completed and DNS refers to hbz server.
