### ISSUE TITLE
Update news box with save the date for SWIB24

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#43]

**Comment by acka47** [comment]
I assume I will have to adjust https://github.com/swibcon/swib.org/blob/main/etc/html_tmpl/newsbox.md.inc and the @phu2 or @dr0i will rebuild the page. (It seems to have worked like this for the last change with https://github.com/swibcon/swib.org/commit/eee6a2a324c385817d7bb897aff8d02ce3e1c56d and then https://github.com/swibcon/swib.org/commit/decdf4863385469d92ce4680562439145f2e8666.)

I could not find the documentation on how we do this. I think we should write it into the README.md shouldn't we?

**Comment by Phu2** [comment]
[Fixed typo](https://github.com/swibcon/swib.org/commit/7e0adbe1fb8e1511c49f536a6a7d79f7676656ba) and deployed to stage http://swib.test.metadaten.nrw/swib23/

**Comment by Phu2** [comment]
> I could not find the documentation on how we do this. I think we should write it into the README.md shouldn't we?

see https://github.com/swibcon/swib.org/pull/44

**Comment by acka47** [comment]
> [Fixed typo](https://github.com/swibcon/swib.org/commit/7e0adbe1fb8e1511c49f536a6a7d79f7676656ba) and deployed to stage http://swib.test.metadaten.nrw/swib23/

Looks good. Please deploy on production.

**Comment by Phu2** [comment]
Deployed to https://swib.org/
