### ISSUE TITLE
Publish CfP for SWIB24

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#45]
The publication o the CfP is scheduled for Wednesday, 2024-04-17.

To Dos for swib.org:

- [x] Create swib24 folder/path
- [x] Add updated CfP text
- [x] Add SWIB24 logo
- [x] Add SWIB24 header image
- [x] Write "general information" text
- [x] Update symlink (swib.org -> swib.org/swib24)

For the start, we will only have the navigation tabs "Home", "General Information" and "Code of Conduct"

**Comment by acka47** [comment]
> Add updated CfP text

The CfP text should be ok now and can be found at https://github.com/swibcon/swib-orga/blob/main/cfp.md

> Add SWIB24 logo

The logo can be found at https://github.com/swibcon/swib-orga/blob/main/swib24/logos/swib24-logo.png. I don't know where to put it in this repo, though...

> Write "general information" text

We might publish the first version of the swib24 page without it (we still don't have that page for SWIB22, see https://swib.org/swib22/general-information.html). However, i think it would be nice to have a page with the core information about how SWIB24 is going to happen.

**Comment by Phu2** [comment]
First draft published at http://swib.test.metadaten.nrw/swib24/
@acka47 Please review

**Comment by Phu2** [comment]
> I don't know where to put it in this repo, though...

Now there is https://github.com/swibcon/swib.org/tree/main/var/html/swib24/images
The missing banner aka header image should be stored in this directory, too. Replace `swib_banner.png.2023` with `swib_banner.png`

**Comment by acka47** [comment]
Thanks, @phu. This already looks very good. We will only need a header image, then, until Wednesday.

**Comment by acka47** [comment]
- [x] We will have to update Julia's affiliation. Already did so in the swib-orga repo, see https://github.com/swibcon/swib-orga/commit/2462071113e52d5d2db81684ed9d4c6c17dbcf50

**Comment by Phu2** [comment]
Temporarily removed banner image https://github.com/swibcon/swib.org/commit/a1da0264a9501e1a97d791824c7d2da82c32c36b

**Comment by Phu2** [comment]
General information updated and published: http://swib.test.metadaten.nrw/swib24/general-information.html

**Comment by acka47** [comment]
Closing. The header image will be provided by ZBW marketing and put online next week.
