### ISSUE TITLE
Publish SWIB24 programme

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#49]
To be published in the beginning of September.

To do:
- [x] Group talks to sessions & design schedule in padlet (Adrian, Anna)
- [x] Make sure that all talks are confirmed, abstracts updated and necessary bios submitted (Adrian, Anna)
- [x] Create sessions and assign talks in ConfTool (Anna)
- [x] Export Conftool data (Phu)
- [x] Build website (Phu)
- [x] Replace CfP by homepage text
- [x] Add links to forum (#53 )
- [x] Publish to production

**Comment by Phu2** [comment]
Do we have an updated text for the homepage already? See this commit from last year: https://github.com/swibcon/swib.org/pull/24/files

**Comment by acka47** [comment]
> Do we have an updated text for the homepage already?

Now. Will look into it.

**Comment by acka47** [comment]
Done. Closing. We will announce it tomorrow.
