### ISSUE TITLE
Wrong links from programme page to speakers page

### ISSUE THREAD

**Issue by Phu2** [swibcon/swib.org#50]
Example: "A web-based translation interface for the MeSH vocabulary" in http://swib.test.metadaten.nrw/swib24/programme.html

"Lukas Geist" is not linked although he is on the speakers page. 

"Leyla Jael Castro" is linked to "Lukas Geist", she is not mentioned on the speakers page.

The author id (used as link fragments) seems to be generated from the email field, see https://github.com/swibcon/swib.org/blob/main/bin/create_website.pl#L133

Only authors with current bio are listed on the speakers page, see https://github.com/swibcon/swib.org/blob/main/bin/create_website.pl#L266

**Comment by Phu2** [comment]
@acka47 Please check in conftool wether
- Lukas Geist has an email
- Leyla Jael Castro has an email and an accepted bio

**Comment by acka47** [comment]
We just wen through all the links and corrected the mistakes. Closing.
