### ISSUE TITLE
Add links to discourse forum

### ISSUE THREAD

**Issue by acka47** [swibcon/swib.org#53]
We will (mis)use `<presenting_author_cv>` for adding this link in ConfTool (see also https://forum.swib.org/t/finalize-programme-on-website/142/2).

- [x] Add links to "Short CV of presenting author in ConfTool
- [x] Update page build script to include the link behind a Discourse icon after each workshop/talk title

**Comment by acka47** [comment]
As discussed via chat: A tool tip behind/over the Discourse icon should read "Join the discussion on the SWIB forum" .

**Comment by Phu2** [comment]
Added Tooltip via `title` attribute for now.

**Comment by acka47** [comment]
Done, deployed, Closing
